on: workflow_dispatch

name: Java_containerapp_deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    
    - name: 'Login via Azure CLI'
      uses: Azure/login@v1
      with:
       creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

    
    - uses: azure/docker-login@v1
      with:
        login-server: testregistry4572.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t testregistry4572.azurecr.io/javasampleapp:${{ github.sha }}
        docker push testregistry4572.azurecr.io/javasampleapp:${{ github.sha }} 
        
    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
            resource-group: serviceprinciple
            dns-name-label: https://javacontainerapp.politegrass-caa43753.eastus.azurecontainerapps.io
            image: testregistry4572.azurecr.io/javasampleapp:${{ github.sha }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: javacontainerapp
            location: 'East US'    
      
   # - uses: azure/webapps-deploy@v2
    #  with:
     #   app-name: 'javacontainerapp'
      #  images: 'testregistry4572.azurecr.io/javasampleapp:${{ github.sha }}'
    
    #- name: Azure logout
     # run: |
      #  az logout
