on: workflow_dispatch

name: Java_containerapp_deployment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    
    - name: 'Login via Azure CLI'
      uses: Azure/login@v1
      with:
       creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

    
    - uses: azure/docker-login@v1
      with:
        login-server: testregistry4572.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t testregistry4572.azurecr.io/javasampleapp:${{ github.sha }}
        docker push testregistry4572.azurecr.io/javasampleapp:${{ github.sha }} 


  deploy:
      runs-on: ubuntu-latest
      needs: build
      
      steps:
      - name: 'Login via Azure CLI'
        uses: Azure/login@v1
        with:
         creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
    
      - uses: azure/docker-login@v1
        with:
         login-server: testregistry4572.azurecr.io
         username: ${{ secrets.REGISTRY_USERNAME }}
         password: ${{ secrets.REGISTRY_PASSWORD }}
    
      - name: Deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
         appSourcePath: ${{ github.workspace }}/src 
         containerAppName: javacontainerapp
         containerAppEnvironment: managedEnvironment-serviceprincipl-9710
         resourceGroup: serviceprinciple
         imageToDeploy: testregistry4572.azurecr.io/javasampleapp:${{ github.sha }} 
